
INIT_RECT_X = 50
INIT_RECT_Y = 50
INIT_RECT_WIDTH = 200
INIT_RECT_HEIGHT = 100

INIT_CRC_X = 50
INIT_CRC_Y = 50
INIT_CRC_RADIUS = 70

OVAL_SIZE = 10

INIT_BDR_X = 50
INIT_BDR_Y = 50
INIT_BDR_WIDTH = None
INIT_BDR_HEIGHT = None
INIT_BDR_LENGTH = 400

PROC_FONT = ('DejaVu Sans Mono', 14)
PROC_FONT_B = ('DejaVu Sans Mono', 14, "bold")
PROC_TEXT_COLOR = "cornflower blue"

STOR_FONT = ('DejaVu Sans Mono', 14)
STOR_FONT_B = ('DejaVu Sans Mono', 14, "bold")
STOR_TEXT_COLOR = "cornflower blue"

CLINE_COLOR = "khaki3"
CLINE_ARROW_SHAPE = (8, 12, 15)
